// <auto-generated />
using System;
using FileSimulator.ControlApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FileSimulator.ControlApi.Migrations
{
    [DbContext(typeof(MetricsDbContext))]
    partial class MetricsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("FileSimulator.ControlApi.Data.Entities.AlertEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_resolved");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<int>("Severity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("triggered_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredAt")
                        .HasDatabaseName("ix_alerts_triggered_at");

                    b.HasIndex("Type", "Source", "IsResolved")
                        .HasDatabaseName("ix_alerts_type_source_resolved");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("FileSimulator.ControlApi.Data.Entities.HealthHourly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("AvgLatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("avg_latency_ms");

                    b.Property<int>("HealthyCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("healthy_count");

                    b.Property<DateTime>("HourStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("hour_start");

                    b.Property<double?>("MaxLatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("max_latency_ms");

                    b.Property<double?>("MinLatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("min_latency_ms");

                    b.Property<double?>("P95LatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("p95_latency_ms");

                    b.Property<int>("SampleCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sample_count");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<string>("ServerType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("server_type");

                    b.HasKey("Id");

                    b.HasIndex("ServerId", "HourStart")
                        .HasDatabaseName("ix_health_hourly_server_hour");

                    b.ToTable("health_hourly", (string)null);
                });

            modelBuilder.Entity("FileSimulator.ControlApi.Data.Entities.HealthSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_healthy");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("REAL")
                        .HasColumnName("latency_ms");

                    b.Property<string>("ServerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("server_id");

                    b.Property<string>("ServerType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("server_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_health_samples_timestamp");

                    b.HasIndex("ServerId", "Timestamp")
                        .HasDatabaseName("ix_health_samples_server_timestamp");

                    b.ToTable("health_samples", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
