{{- if .Values.kafkaUi.enabled }}
---
# Kafka-UI Deployment (Provectus)
# Power-user management interface for Kafka cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "file-simulator.fullname" . }}-kafka-ui
  namespace: {{ include "file-simulator.namespace" . }}
  labels:
    {{- include "file-simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "file-simulator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: kafka-ui
  template:
    metadata:
      labels:
        {{- include "file-simulator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: kafka-ui
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "file-simulator.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: kafka-ui
          image: "{{ .Values.kafkaUi.image.repository }}:{{ .Values.kafkaUi.image.tag }}"
          imagePullPolicy: {{ .Values.kafkaUi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: KAFKA_CLUSTERS_0_NAME
              value: "file-simulator"
            - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
              value: "{{ include "file-simulator.fullname" . }}-kafka:9092"
            - name: DYNAMIC_CONFIG_ENABLED
              value: "true"
            - name: SERVER_PORT
              value: "8080"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.kafkaUi.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
# Kafka-UI Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "file-simulator.fullname" . }}-kafka-ui
  namespace: {{ include "file-simulator.namespace" . }}
  labels:
    {{- include "file-simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
spec:
  type: {{ .Values.kafkaUi.service.type }}
  ports:
    - port: {{ .Values.kafkaUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.kafkaUi.service.type "NodePort" }}
      nodePort: {{ .Values.kafkaUi.service.nodePort }}
      {{- end }}
  selector:
    {{- include "file-simulator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kafka-ui
{{- end }}
