{{- if .Values.management.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "file-simulator.fullname" . }}-filebrowser-config
  namespace: {{ include "file-simulator.namespace" . }}
  labels:
    {{- include "file-simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
data:
  .filebrowser.json: |
    {
      "port": 8080,
      "baseURL": "",
      "address": "0.0.0.0",
      "log": "stdout",
      "database": "/database/filebrowser.db",
      "root": "/srv"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "file-simulator.fullname" . }}-management
  namespace: {{ include "file-simulator.namespace" . }}
  labels:
    {{- include "file-simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "file-simulator.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: management
  template:
    metadata:
      labels:
        {{- include "file-simulator.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: management
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "file-simulator.serviceAccountName" . }}
      {{- end }}
      containers:
        - name: filebrowser
          image: "{{ .Values.management.image.repository }}:{{ .Values.management.image.tag }}"
          imagePullPolicy: {{ .Values.management.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: FB_DATABASE
              value: /database/filebrowser.db
            - name: FB_ROOT
              value: /srv
            - name: FB_LOG
              value: stdout
            - name: FB_NOAUTH
              value: "false"
          volumeMounts:
            - name: data
              mountPath: /srv
            - name: database
              mountPath: /database
            - name: config
              mountPath: /.filebrowser.json
              subPath: .filebrowser.json
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.management.resources | nindent 12 }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "file-simulator.fullname" . }}-pvc
        - name: database
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "file-simulator.fullname" . }}-filebrowser-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "file-simulator.fullname" . }}-management
  namespace: {{ include "file-simulator.namespace" . }}
  labels:
    {{- include "file-simulator.labels" . | nindent 4 }}
    app.kubernetes.io/component: management
spec:
  type: {{ .Values.management.service.type }}
  ports:
    - port: {{ .Values.management.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if eq .Values.management.service.type "NodePort" }}
      nodePort: {{ .Values.management.service.nodePort }}
      {{- end }}
  selector:
    {{- include "file-simulator.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: management
{{- end }}
