<#
.SYNOPSIS
    Updates Windows hosts file with Minikube IP for file-simulator services.

.DESCRIPTION
    Gets the current Minikube IP and updates the Windows hosts file with
    stable hostnames for file-simulator services. Requires Administrator privileges.

.PARAMETER Profile
    Minikube profile name. Default: file-simulator

.PARAMETER Hostname
    Base hostname to use. Default: file-simulator.local

.EXAMPLE
    .\Setup-Hosts.ps1

.EXAMPLE
    .\Setup-Hosts.ps1 -Profile "my-cluster" -Hostname "simulator.local"
#>

param(
    [string]$Profile = "file-simulator",
    [string]$Hostname = "file-simulator.local"
)

$ErrorActionPreference = "Stop"

# Check if running as Administrator
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "This script requires Administrator privileges to modify the hosts file." -ForegroundColor Red
    Write-Host "Please run PowerShell as Administrator and try again." -ForegroundColor Yellow
    exit 1
}

# Get Minikube IP
Write-Host "Getting Minikube IP for profile '$Profile'..." -ForegroundColor Cyan
try {
    $minikubeIp = minikube ip -p $Profile 2>&1
    if ($LASTEXITCODE -ne 0) {
        throw "Failed to get Minikube IP. Is the cluster running?"
    }
    Write-Host "Minikube IP: $minikubeIp" -ForegroundColor Green
} catch {
    Write-Host "Error: $_" -ForegroundColor Red
    Write-Host "Make sure Minikube is running: minikube start -p $Profile" -ForegroundColor Yellow
    exit 1
}

# Hosts file path
$hostsPath = "$env:SystemRoot\System32\drivers\etc\hosts"

# Read current hosts file
$hostsContent = Get-Content $hostsPath -Raw

# Define hostnames to add (static infrastructure services)
$hostnames = @(
    $Hostname,
    "api.$Hostname",
    "dashboard.$Hostname",
    "kafka.$Hostname"
)

# Marker for our entries
$markerStart = "# BEGIN file-simulator"
$markerEnd = "# END file-simulator"

# Remove old entries if they exist
if ($hostsContent -match "$markerStart[\s\S]*?$markerEnd") {
    $hostsContent = $hostsContent -replace "$markerStart[\s\S]*?$markerEnd\r?\n?", ""
    Write-Host "Removed old file-simulator entries" -ForegroundColor Yellow
}

# Build new entries
$newEntries = @()
$newEntries += $markerStart
$newEntries += "# Auto-generated by Setup-Hosts.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
$newEntries += "# Minikube profile: $Profile"
foreach ($hostname in $hostnames) {
    $newEntries += "$minikubeIp`t$hostname"
}
$newEntries += $markerEnd

# Append new entries
$hostsContent = $hostsContent.TrimEnd() + "`r`n`r`n" + ($newEntries -join "`r`n") + "`r`n"

# Write hosts file
Set-Content -Path $hostsPath -Value $hostsContent -Force -NoNewline

Write-Host "`nHosts file updated successfully!" -ForegroundColor Green
Write-Host "`nAdded entries:" -ForegroundColor Cyan
foreach ($host in $hostnames) {
    Write-Host "  $minikubeIp  $host" -ForegroundColor White
}

# Flush DNS cache
Write-Host "`nFlushing DNS cache..." -ForegroundColor Cyan
ipconfig /flushdns | Out-Null
Write-Host "DNS cache flushed" -ForegroundColor Green

# Test connectivity
Write-Host "`nTesting connectivity..." -ForegroundColor Cyan
$testResult = Test-Connection -ComputerName $Hostname -Count 1 -Quiet
if ($testResult) {
    Write-Host "Successfully resolved $Hostname to $minikubeIp" -ForegroundColor Green
} else {
    Write-Host "Warning: Could not ping $Hostname (this may be normal if ICMP is blocked)" -ForegroundColor Yellow
}

# Print connection info
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host " File Simulator Connection Info" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Dashboard:    http://$Hostname`:30080" -ForegroundColor White
Write-Host "Control API:  http://$Hostname`:30500" -ForegroundColor White
Write-Host ""
Write-Host "Protocol Servers:" -ForegroundColor Yellow
Write-Host "  FTP:        $Hostname`:30021" -ForegroundColor White
Write-Host "  SFTP:       $Hostname`:30022" -ForegroundColor White
Write-Host "  HTTP:       http://$Hostname`:30088" -ForegroundColor White
Write-Host "  S3/MinIO:   http://$Hostname`:30900" -ForegroundColor White
Write-Host "  SMB:        \\$Hostname (via tunnel)" -ForegroundColor White
Write-Host "  NFS:        $Hostname`:32049" -ForegroundColor White
Write-Host ""
Write-Host "Get full connection details:" -ForegroundColor Yellow
Write-Host "  curl http://$Hostname`:30500/api/connection-info" -ForegroundColor White
Write-Host ""
